apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: web-ui
spec:
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
      - image: platiagro/web-ui:0.0.1
        name: web-ui
        ports:
        - containerPort: 80