apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: registry-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 81
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: registry
spec:
  gateways:
    - registry-gateway
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: /
      rewrite:
        uri: /
      route:
        - destination:
            host: $(service).$(ui-namespace).svc.$(ui-clusterDomain)
            port:
              number: 5000
      timeout: 300s
