apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: minio-service
spec:
  gateways:
  - kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /minio
    rewrite:
      uri: /minio
    route:
    - destination:
        host: minio-service.$(namespace).svc.$(clusterDomain)
        port:
          number: 9000
