apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: registry
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - image: registry:2.7.1
          name: registry
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /var/lib/registry
              name: registry-persistent-storage
      volumes:
        - name: registry-persistent-storage
          persistentVolumeClaim:
            claimName: registry-pv-claim
