apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
configMapGenerator:
  - name: ui-parameters
    env: params.env
resources:
  - deployment.yaml
  - service.yaml
  - persistent-volume-claim.yaml
vars:
  - name: registryPvcName
    objref:
      kind: ConfigMap
      name: ui-parameters
      version: v1
    fieldref:
      fieldpath: data.registryPvcName
  - name: service
    objref:
      kind: Service
      name: registry
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: ui-namespace
    objref:
      kind: Service
      name: registry
      apiVersion: v1
    fieldref:
      fieldpath: metadata.namespace
  - name: ui-clusterDomain
    objref:
      kind: ConfigMap
      name: ui-parameters
      version: v1
    fieldref:
      fieldpath: data.uiClusterDomain
