apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: foragri-frutas
spec:
  selector:
    matchLabels:
      app: foragri-frutas
  template:
    metadata:
      labels:
        app: foragri-frutas
    spec:
      containers:
      - image: platiagro/foragri-frutas:0.0.1
        name: foragri-frutas
        ports:
        - containerPort: 80