apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: datasets
  name: datasets
spec:
  selector:
    matchLabels:
      app: datasets
  template:
    metadata:
      labels:
        app: datasets
    spec:
      containers:
        - name: datasets
          env:
            - name: MINIO_ENDPOINT
              value: "minio-service.kubeflow:9000"
            - name: MINIO_ACCESS_KEY
              value: "minio"
            - name: MINIO_SECRET_KEY
              value: "minio123"
          image: platiagro/datasets:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
