apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: projects
spec:
  selector:
    matchLabels:
      app: projects
  template:
    metadata:
      labels:
        app: projects
    spec:
      containers:
        - image: platiagro/projects:0.1.0
          name: projects
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_ROOT_PASSWORD
              value: ""
            - name: DB_DATABASE
              value: "platiagro"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
