apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: pipelines
spec:
  selector:
    matchLabels:
      app: pipelines
  template:
    metadata:
      labels:
        app: pipelines
    spec:
      containers:
      - image: platiagro/pipelines:0.0.1
        name: pipelines
        ports:
        - containerPort: 8080