apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: pipelines
  name: pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipelines
subjects:
  - kind: ServiceAccount
    name: pipelines
