apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: pipelines
  name: pipelines
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - create
      - get
      - list
  - apiGroups:
      - "kubeflow.org"
    resources:
      - viewers
    verbs:
      - create
      - get
      - list
      - watch
      - delete
